### ISSUE TITLE
BITCOIN_RPCUSER in lnd_litecoin

### ISSUE THREAD

**Issue by mikeghen** [crypdex/blackbox#20]
I ran into this installing the `lnd_litecoin` service: https://github.com/crypdex/blackbox/blob/fafced9265a89c7862aef46f8a87c008fadad7e5/services/lnd_litecoin/scripts/prestart.sh#L4

Seems like this should be `LITECOIN` not `BITCOIN`

**Comment by dmichael** [comment]
Thanks Mike. This has been removed in the `conf-files` branch and will be merged today.

**Comment by dmichael** [comment]
Merged and closed.
