### ISSUE TITLE
Support for lndash as a service

### ISSUE THREAD

**Issue by mikeghen** [crypdex/blackbox#21]
This issue is a request to package https://github.com/djmelik/lndash as a service, currently I just run it from `/opt` when I need it

**Comment by dmichael** [comment]
Any secrets to getting this up?

lndash does not look maintained. The docker image has been removed. After building and pushing my own image, i just get internal server errors with this

```
```

**Comment by dmichael** [comment]
I just noticed this message in the logs
"Peer name lnd_bitcoin is not in peer certificate"
I am pointing lndash to the right tls cert, but it doesnt seem to like it. Blackbox is not taking any special steps to generate these certs ... should it? I wonder if there is a usecase that requires these peer names other than lndash.

**Comment by dmichael** [comment]
Because the `blackbox.yml` file is just Docker Compose - just can just add your service there.
